### ISSUE TITLE
Hardcoded Values

### ISSUE THREAD

**Issue by VoyTechnology** [CanOpener/PongPlusPlus-Server#3]
In multiple places there are hardcoded values that make it not possible to run the server out of the box.

Examples:
**https://github.com/CanOpener/PongPlusPlus-Server/blob/master/main.go#L10**

> This should be a generic directory that is on all systems and user has permissions to edit it (`/tmp`)

**https://github.com/CanOpener/PongPlusPlus-Server/blob/master/main.go#L12**

> In this case it would be better to just specify `:3000` so the server listens on all interfaces, and not just on `localhost`

**Comment by CanOpener** [comment]
Resolved in @654ff37f50c6356fa9681b8e81887e2b76510f92
Take a look and close the issue if you think it's ok.

**Comment by VoyTechnology** [comment]
Yup looks much better, but I am not sure why some flags are capitalized
